### ISSUE TITLE
Running the contributed command:'iar.syncIarProjectFile' failed.

### ISSUE THREAD

**Issue by AlexYong305** [pluyckx/iar-vsc#4] opened 2018-11-09 07:04 UTC
There are two .ewp in .eww,when I run **select project** to change to another .ewp and **sync project file**     , I see **Running the contributed command:'iar.syncIarProjectFile' failed.**

**Comment by pluyckx** [comment] 2018-11-09 11:19
Thank you for the report.

I have verified this in one of my own projects, but here it works fine. Could you give some more information?
- Which compiler are you using (ARM, AVR, STM8, ...)?
- What is the version of your compiler?
- If possible, could you add your ewp files?
- Am I correct that for one of the two ewp files the *sync project file* is working correctly?

**Comment by ablewitt** [comment] 2018-11-09 12:00
I came across this bug when I first installed the extension. If I remove the line for the IAR install location from **iar.json** and restart VS code I could successfully run **sync project file**.

I have since moved to a different machine and the issue did not reproduce it self (same project with 2 .ewp files). Sorry I can't help with anymore information as I have since blown the installation away, but it was stock standard IAR ARM Workbench installation downloaded within the last week.

**Comment by pluyckx** [comment] 2018-11-10 21:53
Ok, I will keep an eye on this issue.

**Comment by pluyckx** [comment] 2018-11-10 22:30
For now I have set this to won't fix as we can not reproduce it and some changes in error handling are in the pipeline.

**Comment by AlexYong305** [comment] 2018-11-14 11:02
notificationsAlerts.ts:38 Error: Running the contributed command:'iar.syncIarProjectFile' failed.
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:460:256)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:460:648)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:757)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:423)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:15)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:606:957)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
t.onDidNotificationChange @ notificationsAlerts.ts:38

I got this at developer tools,is it help?

**Comment by pluyckx** [comment] 2018-11-18 16:13
Thank you for the trace. I will see if I can reproduce the issue.

**Comment by pluyckx** [comment] 2018-11-21 21:30
I will further investigate the issue. Today I was able to reproduce the issue. Unfortunately it is not easy to reproduce, so it is possible it will take some time to fix it.

**Comment by sbomber** [comment] 2018-12-05 21:35
Here is the contents of iar-vsc.json

```
{
    "iar_location": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.0",
    "ewp_location": "c:\\MFG_SVN\\daVinci\\Valve\\V1\\trunk\\500GRD_Valve.ewp"
}
```

**Comment by sbomber** [comment] 2018-12-05 21:42
First, let me say thank you for the extension!

I noticed this morning when I was using a different code set the error did not occur.  I just verified this fact.  I am wondering if it has to do with the version of IAR EWB and maybe the changed something within the project (ewp) file.  This is the contents of iar-vsc.json in which the Sync does not fail.

```
{
    "iar_location": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.1",
    "ewp_location": "c:\\MFG_SVN\\daVinci\\App2\\500App\\500.ewp"
}
```

**Comment by sbomber** [comment] 2018-12-07 14:02
Hi Philip,
I took some time to debug this.  The issue is indeed when there are multiple mirco IAR installations.   This issue is in ```iar.ts - findCompilerPath```.  It appears you were never expecting more than one micro compiler.  We arrive at this function when issuing the ```IAR: Select Installation```.  The difficulty with fixing this is there is a possibility the extension does not know the desired project file yet.  It seems to me in this case, the extension would need to detect multiple mirco compilers, the jump the code that runs when ```IAR: Select Project``` is called, have the user select the project file, then search the project file for the correct micro.

If you want assistance with this I am willing to help.  

![image](https://user-images.githubusercontent.com/37964811/49652013-70878200-f9f6-11e8-94bd-ab22b0fa447c.png)

**Comment by pluyckx** [comment] 2018-12-11 18:40
sbomber, I create a new issue for what you reported. I saw that the issue you describe is different from that of AlexYong35.

**Comment by sbomber** [comment] 2018-12-12 00:17
I agree

On Dec 11, 2018, at 12:40 PM, Philip Luyckx <notifications@github.com<mailto:notifications@github.com>> wrote:


sbomber, I create a new issue for what you reported. I saw that the issue you describe is different from that of AlexYong35.

**Comment by pluyckx** [comment] 2019-01-04 23:34
The sync command is completely rewritten. I will close this issue, but in case someone encounters this issue again, please let me know and I will reopen this issue,

**Closed by pluyckx** 2019-01-04 23:34 UTC
Labels: bug
